### ISSUE TITLE
Add a topic named "scoop-bucket" to this project

### ISSUE THREAD

**Issue by rasa** [zhoujin7/tomato#1]
See https://github.com/rasa/scoop-directory/blob/443a7b14934119ed86e6015d024afa02686c2a01/maintenance/github-crawler.py#L152

![2019-11-20_09-36-19PMchrome-rasascoops_A_bucket_of_tasty_scoop_flavored_apps](https://user-images.githubusercontent.com/220772/69306930-00a9e180-0bde-11ea-825d-7ff51c41b146.png)

**Comment by zhoujin7** [comment]
Done.
