### ISSUE TITLE
OracleJDK11@11.0.14: download via aria2 failed

### ISSUE THREAD

**Issue by xiangagou** [zhoujin7/tomato#10]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://downloads.sourceforge.net/project/tomato-extra/apps/jdk-11.0.14_windows-x64_bin.zip
    dir=C:\Users\SYLINCOM\scoop\cache
    out=OracleJDK11#11.0.14#https_master.dl.sourceforge.net_project_tomato-extra_apps_jdk-11.0.14_windows-x64_bin.zip

ERROR & 'C:\Users\SYLINCOM\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\SYLINCOM\scoop\cache\OracleJDK11.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=20968 --continue --summary-interval=0 --auto-save-interval=1 --all-proxy='127.0.0.1:7890'

**Comment by zhoujin7** [comment]
太忙了 最近都没时间

**Comment by zhoujin7** [comment]
修复了oraclejdk 8 11 17 都更新到最新版
