### ISSUE TITLE
YAPA2 outdated version

### ISSUE THREAD

**Issue by kiksilog** [zhoujin7/tomato#11]
Could you please update YAPA2 version to v2.0.179?

Thank you.

**Comment by zhoujin7** [comment]
最近没时间哈 你先自己维护一份好了

**Comment by zhoujin7** [comment]
app_name        app_version     bucket_repo
yapa2           2.0.190         https://github.com/ScoopInstaller/Extras
scoop extras已经有了. 这里就不维护它了.
