### ISSUE TITLE
What is the difference between your HBuilderX Full and HBuilderX version?

### ISSUE THREAD

**Issue by dong-lufei** [zhoujin7/tomato#12]
[zhoujin7/tomato]

HBuilderX Full
HBuilderX

**Comment by zhoujin7** [comment]
一个全功能版 一个精简版 和官方的保持一致

**Comment by dong-lufei** [comment]
@zhoujin7 官方我只看到 windows和mac 的 正式版 和 Alpha版本，你说的和官方保持一致指的是全功能版和官方的一致还是精简版？

**Comment by zhoujin7** [comment]
@dong-lufei 我好久没用hbuilerx了  你需要的话自己弄一下

**Comment by dong-lufei** [comment]
> @dong-lufei 我好久没用hbuilerx了 你需要的话自己弄一下

我不会弄那么高深的，我只是个 scoop 新手

**Comment by zhoujin7** [comment]
> > @dong-lufei 我好久没用hbuilerx了 你需要的话自己弄一下
> 
> 我不会弄那么高深的，我只是个 scoop 新手
给我打赏点, 可以帮你搞定. 本来这个仓库只是我自己用的. 我还要忙别的事情.
