### ISSUE TITLE
ShadowsocksR@5.1.9: hash check failed

### ISSUE THREAD

**Issue by fishen** [zhoujin7/tomato#2]
哈希值不对
Expected:    fe56a556da049b7ffdeca4d0a5dcae675aa288e5baa2676ee2493c3eb352254c
Actual:      4260189395ee3dac6431c372981d8774794c832b220bb79d9b02dcc0a672e385

经手动测试，下载的文件哈希值为后者。

**Comment by zhoujin7** [comment]
晚点搞

**Comment by zhoujin7** [comment]
改好了... 我现在用clash了 用的机场是v2协议... 🤷‍♀️🤷‍♀️🤷‍♀️
