### ISSUE TITLE
qtdesigner@5.15.0: Hash check failed

### ISSUE THREAD

**Issue by furtabs** [zhoujin7/tomato#8]
Hash check failed!
App:         tomato/qtdesigner
URL:         https://github.com/PyQt5/QtDesigner/releases/download/5.15.0/Windows.7z
First bytes: 55 122 188 175 39 28 0 3
Expected:    0bf572ff2adbf63e733fa296e47b524c03aa2bce1aabe34f9d9775ab7c5d8064
Actual:      4999a99ca8df9565b2d3831d6605572d8c784149a09321380272706df7a0111d

**Comment by zhoujin7** [comment]
暂时没时间弄.

**Comment by zhoujin7** [comment]
已修复
