### ISSUE TITLE
[Request]ShadowsocksR-Windows大幅度更新，请更新一下bucket

### ISSUE THREAD

**Issue by DoveBoy** [zhoujin7/tomato#9]
[ShadowsocksR-Windows](https://github.com/HMBSbige/ShadowsocksR-Windows)进行了大幅度更新，原版本还停留在5.1.9，请更新一下bucket，感谢！

**Comment by zhoujin7** [comment]
我现在不用ssr了, 你先自己弄吧. 最多佛系更新.
